
This file will contain all notes taken during the course "Applied Cloud
Computing, 5.0 hp" at Uppsala University.

* Applied Cloud Computing, 10.0 hp
** Lectures
** Labs
** Seminar

    == Q3 ==

    Try to, from a technological point of view, relate the following
    products/cloud providers, frameworks and tools to each other, both
    historically and in the technological problems they have addressed. Is there
    some logical progression in a seemingly fragmented ecosystem?

    + OpenStack
    + Rackspace
    + Eucalyptus
    + Amazon EC2
    + Google App Engine
    + Cloud Foundry
    + OpenShift
    + Mesos
    + Kubernetes

*** Articles from Student Portal
**** DONE p13-bonomi.pdf
    
    The article argues that a new compute paradigm should be created, called Fog
    Computing, that shall solve issues that currently are present in Cloud
    Computing. The Fog shall provide localized, geographically aware,
    low-latency networking for devices that require such things.

    In short, the Fog will be a low-latency layer between a end-user, or device,
    and the cloud.

**** TODO googlemapreduce.pdf

    MapReduce := reduce( [ map(key, val) ] )
    MapReduce : [(key, val)] --> [(key, val)]

    map : (key, value) --> (key, value)

    reduce : [(key, value)] --> (key, value)
    
**** DONE CeleryIPythonMpi4py.pdf

    Python, in general, is a good way of running Many-Task Computing (MTC) jobs,
    and the Python libraries IPython and Celery are two good libraries to use
    when constructing MTC clusters.

**** DONE CloudElasticityElmroth.pdf

    The paper shows that the algorithm developed by the authors is better at
    handling horizontal scaling of cloud platforms and demonstrate that it will
    decrease the likelihood of cloud providers violating the service-level
    agreement (SLA).

**** TODO CloudKon.pdf

    

** Project
